---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "print"
      debug:
        msg: "Hello World"

    - name: "update apt packages."
      become: true
      apt:
        update_cache: true

    - name: "upgrade packages"
      become: true
      apt:
        name: "*"
        state: latest

    - name: "install htop"
      package:
        name: htop